"""Description of migration

Revision ID: 262408d81ba8
Revises: 
Create Date: 2024-05-05 12:04:31.264500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262408d81ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_extraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_extraction_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_extraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_extraction_email'))

    op.drop_table('text_extraction')
    # ### end Alembic commands ###
